In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error

### Jan 2020

In [41]:
df1=pd.read_csv(r"E:\Project- Flight Delay\January 2020 raw\Complete Jan Raw.csv")

In [3]:
len(df)

607346

In [42]:
df1=df1[df1['DEST']=='SFO'] #arrivals to SFO
len(df1)

13686

In [43]:
df1=df1[df1['ARR_DELAY'].notnull()] # removing null values rows(includes cancelled and diverted flights)
len(df1)

13484

13686-13484=202 flights were cancelled or diverted due to bad airport condition at origin or destination

In [44]:
df1['JOURNEY_DELAY']=df1['ACTUAL_ELAPSED_TIME']-df1['CRS_ELAPSED_TIME']

In [46]:
df1.to_csv(r'E:\Project- Flight Delay\Nov 2019\Jan Complete SFO.csv')

### December 2019

In [18]:
df2=pd.read_csv(r"E:\Project- Flight Delay\December 2019 raw\Dec Complete Raw .csv")
len(df2)

625763

In [20]:
df2=df2[df2['DEST']=='SFO'] #arrivals to SFO
len(df2)

14038

In [21]:
df2=df2[df2['ARR_DELAY'].notnull()] # removing null values rows(includes cancelled and diverted flights)
len(df2)

13616

422 flights diverted or cancelled

In [22]:
df2['JOURNEY_DELAY']=df2['ACTUAL_ELAPSED_TIME']-df2['CRS_ELAPSED_TIME']

In [34]:
df2.to_csv(r'E:\Project- Flight Delay\Nov 2019\Dec Complete SFO.csv')

### November 2019

In [27]:
df3=pd.read_csv(r"E:\Project- Flight Delay\Nov 2019\Complete Nov Raw.csv")
len(df3)

602453

In [28]:
df3=df3[df3['DEST']=='SFO'] #arrivals to SFO
len(df3)

13538

In [29]:
df3=df3[df3['ARR_DELAY'].notnull()] # removing null values rows(includes cancelled and diverted flights)
len(df3)

13352

185 flights

In [30]:
df3['JOURNEY_DELAY']=df3['ACTUAL_ELAPSED_TIME']-df3['CRS_ELAPSED_TIME']

In [32]:
df3.to_csv(r'E:\Project- Flight Delay\Nov 2019\Complete SFO Nov.csv')

### Concatenate the months data

In [47]:
frames=[df3,df2,df1]

In [48]:
final=pd.concat(frames)
len(df)

40452

In [50]:
df.to_csv(r'E:\Project- Flight Delay\3 months Data\Raw.csv')

#### Convert variables into minutes to make it numeric and continous from 0 to 1440

In [3]:
df=pd.read_csv(r'./Raw.csv')

In [4]:
df.head(2)

Unnamed: 0  YEAR  MONTH  DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER  \
0       11125  2019     11            23            6                OO   
1       11194  2019     11            23            6                OO   

  TAIL_NUM ORIGIN DEST  CRS_DEP_TIME  ...  ACTUAL_ELAPSED_TIME  AIR_TIME  \
0   N267SY    JFK  BNA           840  ...                147.0     126.0   
1   N291SY    JFK  RIC          1930  ...                116.0      73.0   

   DISTANCE  CARRIER_DELAY  WEATHER_DELAY  NAS_DELAY  SECURITY_DELAY  \
0     765.0            NaN            NaN        NaN             NaN   
1     288.0            NaN            NaN        NaN             NaN   

   LATE_AIRCRAFT_DELAY  Unnamed: 29  Unnamed: 27  
0                  NaN          NaN          NaN  
1                  NaN          NaN          NaN  

[2 rows x 32 columns]

In [5]:
def last2digits(num):
    return num%100;
def remdigits(num):
    num=num-last2digits(num)
    return num/100;
def HrstoMins(num):
    return remdigits(num)*60+last2digits(num);
def varInMins(arr):
    temp=HrstoMins(arr)
    List.append(temp)

In [6]:
wheelsOn=np.array(df['WHEELS_ON'])
crsdep=np.array(df['CRS_DEP_TIME'])
wheelsOff=np.array(df['WHEELS_OFF'])
depTime=np.array(df['DEP_TIME'])
crsArrival=np.array(df['CRS_ARR_TIME'])
arrTime=np.array(df['ARR_TIME'])

In [7]:
List=[]
np.vectorize(varInMins, otypes=[float])(wheelsOn)
df['WHEELS_ON_M']=List
List=[]
np.vectorize(varInMins, otypes=[float])(crsdep)
df['CRS_DEP_M']=List
List=[]
np.vectorize(varInMins, otypes=[float])(wheelsOff)
df['WHEELS_OFF_M']=List
List=[]
np.vectorize(varInMins, otypes=[float])(depTime)
df['DEP_TIME_M']=List
List=[]
np.vectorize(varInMins, otypes=[float])(crsArrival)
df['CRS_ARR_M']=List
List=[]
np.vectorize(varInMins, otypes=[float])(arrTime)
df['ARR_TIME_M']=List

/home/deepank/.local/lib/python3.7/site-packages/numpy/lib/function_base.py:2167: RuntimeWarning: invalid value encountered in ? (vectorized)
  outputs = ufunc(*inputs)


**Day of month is corrosponding to scheduled deparuture which accounts for origin airport. To explain the day of flight arrival at destinantion airport, we convert day of month based on scheduled arrival.**

In [8]:
df=pd.read_csv(r'./m1.csv')

In [9]:
df.head(2)

Unnamed: 0  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  OP_UNIQUE_CARRIER  DEST  \
0          13     11             1            5                  3    56   
1          15     11             1            5                  4    56   

   DEP_DELAY  CRS_ELAPSED_TIME  DISTANCE  CRS_DEP_M  ...  Wind Gust  Pressure  \
0         -3               388      2586        410  ...         35     29.91   
1         -6               391      2586        420  ...         29     30.00   

   Condition  Before_Departures  After_Departures  Before_Arrivals  \
0          4                  2                15                0   
1          4                  4                14                2   

   After_Arrivals   TAXI_OUT  WHEELS_OFF_M  Pred_Wheels_On  
0               4  16.989875         424.0             607  
1               5  19.192142         433.0             617  

[2 rows x 27 columns]

# Start from Here

First evaluate M1 model by creating M1 dataset corrosponding to departure time
### Following is the data creation for M2 model

In [10]:
depTime=np.array(df['CRS_DEP_M'])
arrTime=np.array(df['CRS_ARR_M'])
day=np.array(df['DAY_OF_MONTH'])
week=np.array(df['DAY_OF_WEEK'])
month=np.array(df['MONTH'])

In [11]:
def arrivalDay(depTime,arrTime,day,week,month):
    if(depTime>arrTime):
        if(month==11 and day!=30):
            day=day+1
        elif(month==11 and day==30):
            day=1
            month=12
        elif(month==12 and day!=31):
            day=day+1
        elif(month==12 and day==31):
            day=1
            month=1
        elif(month==1 and day!=31):
            day=day+1
        elif(month==1 and day==31): # These flights land on 1st feb thus doesnt lie in current dataset
            day=1
            month=2
        if(week==7):
            week=1
        else:
            week=week+1
    arrivalDay_list.append(day)
    month_list.append(month)
    week_list.append(week)
    return;

In [12]:
arrivalDay_list=[]
month_list=[]
week_list=[]
arrival_day=np.vectorize(arrivalDay,otypes=[float])(depTime,arrTime,day,week,month)
df['DAY_OF_MONTH']=arrivalDay_list
df['MONTH']=month_list
df['DAY_OF_WEEK']=week_list

**Calculate Predicted wheels on time and its corrosponding day of landing at destination airport.**


**sch_Arrival + Dep_delay - Avg_Taxi_in = Estimated_wheels_on**   
   Predicted wheels on bhi day aur month change ho skta h
Avg Taxi-in time=8 min

In [13]:
l=list(range(0,len(df)))

In [19]:
df2=pd.read_csv(r"./Arrival Delay.csv")

In [14]:
def PredWheels(i):
    x=df['CRS_ARR_M'].iloc[i]+df['DEP_DELAY'].iloc[i]-8
    day=df['DAY_OF_MONTH'].iloc[i]
    month=df['MONTH'].iloc[i]
    if(x<0):
        Pred_wheels.append(x+1440)
        if(day==1 and month==12):
            day=30
            month=11
        elif(day==1 and month==1):
            day=31
            month=12
        else:
            day=day-1
        w_day.append(day)
        w_month.append(month)
    elif(x>1440):
        Pred_wheels.append(x-1440)
        if(day==30 and month==11):
            day=1
            month=12
        elif(day==31 and month==12):
            day=1
            month=1
        elif(day==31 and month==1):
            day=1
            month=2
        else:
            day=day+1
        w_day.append(day)
        w_month.append(month)
    else:
        Pred_wheels.append(x)
        w_day.append(day)
        w_month.append(month)
    return;

In [15]:
Pred_wheels=[]
w_day=[]
w_month=[]
t=np.vectorize(PredWheels,otypes=[float])(l)
df['Pred_Wheels_On']=Pred_wheels
df['Weather_Day']=w_day
df['Weather_Month']=w_month

df1 is test data which needs to be created  
df2 is reference data (arrival data)

In [16]:
def create(i):
    x=i
    global df2,t
    b=list(range(0,len(df2)))
    n=np.vectorize(check,otypes=[float])(b,x)
    df1.iloc[i,13:25]=df2.iloc[t,13:26]
    arr_delay.append(df2.iloc[t,-1])
    t=0
    return;

In [17]:
## Use pred_wheels_on, weather_day, weather_month to check the below condition
def check(j,x):
    global t
    if (abs(df2.iloc[j,13]==df1.iloc[x,-3]) and (df2.iloc[j,0]==df1.iloc[x,-1]) and (df2.iloc[j,1]==df1.iloc[x,-2])):
            t=j
            return;
    return;

In [21]:
df1=df
a=list(range(0,len(df1)))
arr_delay=[]
m=np.vectorize(create,otypes=[float])(a)

KeyboardInterrupt: 

In [101]:
from lightgbm import LGBMRegressor
import lightgbm as lgb
lgbm = LGBMRegressor()
model2 = lgb.Booster(model_file=r'./model_light.txt')

In [95]:
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
df1['Wind'] = lb_make.fit_transform(df1['Wind'])
df1['Condition'] = lb_make.fit_transform(df1['Condition'])

In [102]:
arr=model2.predict(df1)

#### After calculating expected arrival delay calulate journey delay=arrival delay - dep delay
update dep delay = dep delay + (journey delay/2)

In [115]:
mean_absolute_error(arr,arr_delay)

8.932007177376056

In [107]:
from sklearn.metrics import mean_squared_error

In [109]:
mean_squared_error(arr,arr_delay,squared=False)

19.71390153223803

In [120]:
from sklearn.metrics import median_absolute_error
median_absolute_error(arr,arr_delay)

NameError: name 'arr_delay' is not defined

In [3265]:
df=pd.read_csv(r"./Arrival Delay.csv")
dfx=df[df['ORIGIN']=='JFK']
dfx=dfx[dfx['ARR_DELAY']==11]
dfx=dfx[dfx['TAXI_OUT']==15]
dfx=dfx[dfx['DEP_DELAY']==-11]

In [3266]:
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
xn=df
xn['OP_UNIQUE_CARRIER'] = lb_make.fit_transform(xn['OP_UNIQUE_CARRIER'])
print(lb_make.transform(['B6']))
xn['ORIGIN'] = lb_make.fit_transform(xn['ORIGIN'])
xn['Wind'] = lb_make.fit_transform(xn['Wind'])
xn['Condition'] = lb_make.fit_transform(xn['Condition'])
df=xn

[2]


In [3267]:
j_delay=dfx['ARR_DELAY']-dfx['DEP_DELAY']
j_delay.describe()

count     1.0
mean     22.0
std       NaN
min      22.0
25%      22.0
50%      22.0
75%      22.0
max      22.0
dtype: float64

In [3268]:
#11942  20
#j_delay=j_delay[j_delay==16]
j_delay

11629    22
dtype: int64

In [3270]:
#p=df.iloc[j_delay.index[0]]
p=df.iloc[11629]
p
#33880

MONTH                  11.00
DAY_OF_MONTH           26.00
DAY_OF_WEEK             2.00
OP_UNIQUE_CARRIER       0.00
ORIGIN                 33.00
DEP_DELAY             -11.00
TAXI_OUT               15.00
CRS_ELAPSED_TIME      407.00
DISTANCE             2586.00
CRS_DEP_M             975.00
DEP_TIME_M            964.00
WHEELS_OFF_M          979.00
CRS_ARR_M            1202.00
Pred_Wheels_On       1183.00
Temperature            52.00
Dew Point              48.00
Humidity               86.00
Wind                   17.00
Wind Speed             21.00
Wind Gust              45.00
Pressure               29.58
Condition               9.00
Before_Arrivals        11.00
After_Arrivals         11.00
Before_Departures       9.00
After_Departures       16.00
ARR_DELAY              11.00
Name: 11629, dtype: float64

In [3271]:
#Index(['month', 'day', 'week', 'airline', 'dest', 'dep_del', 'sch_elp', 'dist',
#       'sch_dep', 'act_dep', 'sch_arr', 'temp', 'dew', 'hum', 'wind', 'w_spd',
#       'gust', 'pres', 'cond', 'bef_dep1', 'aft_dep1', 'bef_arr1', 'aft_arr1']

In [3272]:
point=p.drop(['ORIGIN','TAXI_OUT','WHEELS_OFF_M','Pred_Wheels_On'])
point['DEST']=56
point=point.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'DEST',
       'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M',
       'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind',
       'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'Before_Departures',
       'After_Departures', 'Before_Arrivals', 'After_Arrivals'],axis=1)

In [3273]:
df2=pd.read_csv(r"./Taxi Out Final.csv")

In [3274]:
df2["Wind"]=df2['Wind'].replace(np.nan,"CALM")
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
xn=df2
xn['OP_UNIQUE_CARRIER'] = lb_make.fit_transform(xn['OP_UNIQUE_CARRIER'])
print(lb_make.transform(['B6']))
xn['DEST'] = lb_make.fit_transform(xn['DEST'])
xn['Wind'] = lb_make.fit_transform(xn['Wind'])
xn['Condition'] = lb_make.fit_transform(xn['Condition'])
df2=xn
xn.columns

[3]


Index(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'DEST',
       'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M',
       'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind',
       'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'Before_Departures',
       'After_Departures', 'Before_Arrivals', 'After_Arrivals', 'TAXI_OUT'],
      dtype='object')

In [3275]:
point['OP_UNIQUE_CARRIER']=3

In [3276]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df2)):
    if (abs(df2.iloc[i,9]==point[9]) and (df2.iloc[i,0]==point[0]) and (df2.iloc[i,1]==point[1])):
            t=i
            break
    if (abs(df2.iloc[i,9]-point[9])<=d and (df2.iloc[i,0]==point[0]) and (df2.iloc[i,1]==point[1])):
            t=i
            d=abs(df2.iloc[i,9]-point[9])  
point[11:23]=df2.iloc[t,11:23]

In [3277]:
from lightgbm import LGBMRegressor
import lightgbm as lgb
lgbm = LGBMRegressor()
model1= lgb.Booster(model_file=r'./model_taxi2.txt')

In [3278]:
taxi=model1.predict(point)
taxi[0]

15.50170723334524

In [3279]:
point2=point.rename({"DEST":"ORIGIN"})
point2['ORIGIN']=33
point2['OP_UNIQUE_CARRIER']=2
point2['TAXI_OUT']=taxi[0]
point2['WHEELS_OFF_M']=point['DEP_TIME_M']+taxi[0]
point2['Pred_Wheels_On']=point['CRS_ARR_M']+point['DEP_DELAY']-8
point2=point2.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'ORIGIN',
       'DEP_DELAY', 'TAXI_OUT', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M',
       'DEP_TIME_M', 'WHEELS_OFF_M', 'CRS_ARR_M', 'Pred_Wheels_On',
       'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed',
       'Wind Gust', 'Pressure', 'Condition', 'Before_Arrivals',
       'After_Arrivals', 'Before_Departures', 'After_Departures'],axis=1)

In [3280]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df)):
    if (abs(df.iloc[i,13]==point2[13]) and (df.iloc[i,0]==point2[0]) and (df.iloc[i,1]==point2[1])):
            t=i
            break
    if (abs(df.iloc[i,13]-point2[13])<=d and (df.iloc[i,0]==point2[0]) and (df.iloc[i,1]==point2[1])):
            t=i
            d=abs(df.iloc[i,13]-point2[13])
point2[14:26]=df.iloc[t,14:26]

In [3281]:
from lightgbm import LGBMRegressor
import lightgbm as lgb
lgbm = LGBMRegressor()
model2= lgb.Booster(model_file=r'./model_light.txt')

In [3282]:
arr=model2.predict(point2)
arr

array([2.95817276])

In [3283]:
j_delay2=arr-point2['DEP_DELAY']
j_delay2

array([13.95817276])

In [3284]:
point3=point2
point3['DEP_DELAY']=point3['DEP_DELAY']+(j_delay2/2)
point3['DEP_DELAY']

-4.020913620570286

In [3285]:
point3=point3.drop(['ORIGIN','TAXI_OUT','WHEELS_OFF_M','Pred_Wheels_On'])
point3['DEST']=56
point3=point3.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'DEST',
       'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M',
       'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind',
       'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'Before_Departures',
       'After_Departures', 'Before_Arrivals', 'After_Arrivals'],axis=1)

In [3286]:
point3['OP_UNIQUE_CARRIER']=3

In [3287]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df2)):
    if (abs(df2.iloc[i,9]==point3[9]) and (df2.iloc[i,0]==point3[0]) and (df2.iloc[i,1]==point3[1])):
            t=i
            break
    if (abs(df2.iloc[i,9]-point3[9])<=d and (df2.iloc[i,0]==point3[0]) and (df2.iloc[i,1]==point3[1])):
            t=i
            d=abs(df2.iloc[i,9]-point[9])
point3[11:23]=df2.iloc[t,11:23]

In [3288]:
taxi2=model1.predict(point3)
taxi2[0]

16.0115174578938

In [3289]:
point4=point3.rename({"DEST":"ORIGIN"})
point4['ORIGIN']=33
point4['OP_UNIQUE_CARRIER']=2
point4['TAXI_OUT']=taxi2[0]
point4['WHEELS_OFF_M']=point4['DEP_TIME_M']+taxi2[0]
point4['Pred_Wheels_On']=point4['CRS_ARR_M']+point4['DEP_DELAY']-8
point4=point4.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'ORIGIN',
       'DEP_DELAY', 'TAXI_OUT', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M',
       'DEP_TIME_M', 'WHEELS_OFF_M', 'CRS_ARR_M', 'Pred_Wheels_On',
       'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed',
       'Wind Gust', 'Pressure', 'Condition', 'Before_Arrivals',
       'After_Arrivals', 'Before_Departures', 'After_Departures'],axis=1)

In [3290]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df)):
    if (abs(df.iloc[i,13]==point4[13]) and (df.iloc[i,0]==point4[0]) and (df.iloc[i,1]==point4[1])):
            t=i
            break
    if (abs(df.iloc[i,13]-point4[13])<=d and (df.iloc[i,0]==point4[0]) and (df.iloc[i,1]==point4[1])):
            t=i
            d=abs(df.iloc[i,13]-point4[13])
point4[14:26]=df.iloc[t,14:26]

In [3291]:
arr2=model2.predict(point4)
arr2

array([-4.32423307])

In [3292]:
j_delay3=arr2-point4['DEP_DELAY']
j_delay3

array([-0.30331945])

In [3293]:
point5=point4
point5['DEP_DELAY']=point5['DEP_DELAY']+(j_delay3/2)
point5['DEP_DELAY']

-4.172573344281825

In [3294]:
point5=point5.drop(['ORIGIN','TAXI_OUT','WHEELS_OFF_M','Pred_Wheels_On'])
point5['DEST']=56
point5=point5.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'DEST',
       'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M',
       'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind',
       'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'Before_Departures',
       'After_Departures', 'Before_Arrivals', 'After_Arrivals'],axis=1)

In [3295]:
point5['OP_UNIQUE_CARRIER']=3

In [3296]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df2)):
    if (abs(df2.iloc[i,9]==point5[9]) and (df2.iloc[i,0]==point5[0]) and (df2.iloc[i,1]==point5[1])):
            t=i
            break
    if (abs(df2.iloc[i,9]-point5[9])<=d and (df2.iloc[i,0]==point5[0]) and (df2.iloc[i,1]==point5[1])):
            t=i
            d=abs(df2.iloc[i,9]-point5[9])
point5[11:23]=df2.iloc[t,11:23]

In [3297]:
taxi3=model1.predict(point5)
taxi3[0]

16.0115174578938

In [3298]:
point6=point5.rename({"DEST":"ORIGIN"})
point6['ORIGIN']=33
point6['OP_UNIQUE_CARRIER']=2
point6['TAXI_OUT']=taxi3[0]
point6['WHEELS_OFF_M']=point6['DEP_TIME_M']+taxi3[0]
point6['Pred_Wheels_On']=point6['CRS_ARR_M']+point6['DEP_DELAY']-8
point6=point6.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'ORIGIN',
       'DEP_DELAY', 'TAXI_OUT', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M',
       'DEP_TIME_M', 'WHEELS_OFF_M', 'CRS_ARR_M', 'Pred_Wheels_On',
       'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed',
       'Wind Gust', 'Pressure', 'Condition', 'Before_Arrivals',
       'After_Arrivals', 'Before_Departures', 'After_Departures'],axis=1)

In [3299]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df)):
    if (abs(df.iloc[i,13]==point6[13]) and (df.iloc[i,0]==point6[0]) and (df.iloc[i,1]==point6[1])):
            t=i
            break
    if (abs(df.iloc[i,13]-point6[13])<=d and (df.iloc[i,0]==point6[0]) and (df.iloc[i,1]==point6[1])):
            t=i
            d=abs(df.iloc[i,13]-point6[13])
point6[14:26]=df.iloc[t,14:26]

In [3300]:
arr3=model2.predict(point6)
arr3

array([-4.32423307])

In [3301]:
j_delay4=arr3-point6['DEP_DELAY']
j_delay4

array([-0.15165972])

In [3302]:
point7=point6
point7['DEP_DELAY']=point7['DEP_DELAY']+(j_delay4/2)
point7['DEP_DELAY']

-4.248403206137595

In [3303]:
point7=point7.drop(['ORIGIN','TAXI_OUT','WHEELS_OFF_M','Pred_Wheels_On'])
point7['DEST']=56
point7=point7.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'DEST',
       'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M',
       'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind',
       'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'Before_Departures',
       'After_Departures', 'Before_Arrivals', 'After_Arrivals'],axis=1)

In [3304]:
point7['OP_UNIQUE_CARRIER']=3

In [3305]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df2)):
    if (abs(df2.iloc[i,9]==point7[9]) and (df2.iloc[i,0]==point7[0]) and (df2.iloc[i,1]==point7[1])):
            t=i
            break
    if (abs(df2.iloc[i,9]-point7[9])<=d and (df2.iloc[i,0]==point7[0]) and (df2.iloc[i,1]==point7[1])):
            t=i
            d=abs(df2.iloc[i,9]-point7[9])
point7[11:23]=df2.iloc[t,11:23]

In [3306]:
taxi4=model1.predict(point7)
taxi4[0]

16.0115174578938

In [3307]:
point8=point7.rename({"DEST":"ORIGIN"})
point8['ORIGIN']=33
point8['OP_UNIQUE_CARRIER']=2
point8['TAXI_OUT']=taxi4[0]
point8['WHEELS_OFF_M']=point8['DEP_TIME_M']+taxi4[0]
point8['Pred_Wheels_On']=point8['CRS_ARR_M']+point8['DEP_DELAY']-8
point8=point8.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'ORIGIN',
       'DEP_DELAY', 'TAXI_OUT', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M',
       'DEP_TIME_M', 'WHEELS_OFF_M', 'CRS_ARR_M', 'Pred_Wheels_On',
       'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed',
       'Wind Gust', 'Pressure', 'Condition', 'Before_Arrivals',
       'After_Arrivals', 'Before_Departures', 'After_Departures'],axis=1)

In [3308]:
#df2==taxi,df=arrival
t=0
for i in range(0,len(df)):
    if (abs(df.iloc[i,13]==point8[13]) and (df.iloc[i,0]==point8[0]) and (df.iloc[i,1]==point8[1])):
            t=i
            break
    if (abs(df.iloc[i,13]-point8[13])<=d and (df.iloc[i,0]==point8[0]) and (df.iloc[i,1]==point8[1])):
            t=i
            d=abs(df.iloc[i,9]-point8[9])
point8[14:26]=df.iloc[t,14:26]

In [3309]:
arr4=model2.predict(point8)
arr4

array([-22.81039546])

In [3310]:
j_delay5=arr4-point8['DEP_DELAY']
j_delay5

array([-18.56199226])

In [3311]:
point9=point8
point9['DEP_DELAY']=point9['DEP_DELAY']+(j_delay5/2)
point9['DEP_DELAY']

-13.52939933420986

In [3312]:
point9=point9.drop(['ORIGIN','TAXI_OUT','WHEELS_OFF_M','Pred_Wheels_On'])
point9['DEST']=56
point9=point9.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'DEST',
       'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M',
       'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind',
       'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'Before_Departures',
       'After_Departures', 'Before_Arrivals', 'After_Arrivals'],axis=1)

In [3313]:
point9['OP_UNIQUE_CARRIER']=3

In [3314]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df2)):
    if (abs(df2.iloc[i,9]==point9[9]) and (df2.iloc[i,0]==point9[0]) and (df2.iloc[i,1]==point9[1])):
            t=i
            break
    if (abs(df2.iloc[i,9]-point9[9])<=d and (df2.iloc[i,0]==point9[0]) and (df2.iloc[i,1]==point9[1])):
            t=i
            d=abs(df2.iloc[i,9]-point9[9])
point9[11:23]=df2.iloc[t,11:23]

In [3315]:
taxi5=model1.predict(point9)
taxi5[0]

15.811572944142576

In [3316]:
point10=point9.rename({"DEST":"ORIGIN"})
point10['ORIGIN']=33
point10['OP_UNIQUE_CARRIER']=2
point10['TAXI_OUT']=taxi5[0]
point10['WHEELS_OFF_M']=point10['DEP_TIME_M']+taxi5[0]
point10['Pred_Wheels_On']=point10['CRS_ARR_M']+point10['DEP_DELAY']-8
point10=point10.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'ORIGIN',
       'DEP_DELAY', 'TAXI_OUT', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M',
       'DEP_TIME_M', 'WHEELS_OFF_M', 'CRS_ARR_M', 'Pred_Wheels_On',
       'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed',
       'Wind Gust', 'Pressure', 'Condition', 'Before_Arrivals',
       'After_Arrivals', 'Before_Departures', 'After_Departures'],axis=1)

In [3317]:
#df2==taxi,df=arrival
t=0
for i in range(0,len(df)):
    if (abs(df.iloc[i,13]==point10[13]) and (df.iloc[i,0]==point10[0]) and (df.iloc[i,1]==point10[1])):
            t=i
            break
    if (abs(df.iloc[i,13]-point10[13])<=d and (df.iloc[i,0]==point10[0]) and (df.iloc[i,1]==point10[1])):
            t=i
            d=abs(df.iloc[i,9]-point10[9])
point10[14:26]=df.iloc[t,14:26]

In [3318]:
arr5=model2.predict(point10)
arr5

array([-3.57862874])

In [3319]:
j_delay6=arr5-point10['DEP_DELAY']
j_delay6

array([9.9507706])

In [3320]:
point11=point10
point11['DEP_DELAY']=point11['DEP_DELAY']+(j_delay6/2)
point11['DEP_DELAY']

-8.55401403660371

In [3321]:
point11=point11.drop(['ORIGIN','TAXI_OUT','WHEELS_OFF_M','Pred_Wheels_On'])
point11['DEST']=56
point11=point11.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'DEST',
       'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M',
       'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind',
       'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'Before_Departures',
       'After_Departures', 'Before_Arrivals', 'After_Arrivals'],axis=1)

In [3322]:
point11['OP_UNIQUE_CARRIER']=3

In [3323]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df2)):
    if (abs(df2.iloc[i,9]==point11[9]) and (df2.iloc[i,0]==point11[0]) and (df2.iloc[i,1]==point11[1])):
            t=i
            break
    if (abs(df2.iloc[i,9]-point11[9])<=d and (df2.iloc[i,0]==point11[0]) and (df2.iloc[i,1]==point11[1])):
            t=i
            d=abs(df2.iloc[i,9]-point11[9])
point11[11:23]=df2.iloc[t,11:23]

In [3324]:
taxi6=model1.predict(point11)
taxi6[0]

16.075079854098764

In [3325]:
point12=point11.rename({"DEST":"ORIGIN"})
point12['ORIGIN']=33
point12['OP_UNIQUE_CARRIER']=2
point12['TAXI_OUT']=taxi6[0]
point12['WHEELS_OFF_M']=point12['DEP_TIME_M']+taxi6[0]
point12['Pred_Wheels_On']=point12['CRS_ARR_M']+point12['DEP_DELAY']-8
point12=point12.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'ORIGIN',
       'DEP_DELAY', 'TAXI_OUT', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M',
       'DEP_TIME_M', 'WHEELS_OFF_M', 'CRS_ARR_M', 'Pred_Wheels_On',
       'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed',
       'Wind Gust', 'Pressure', 'Condition', 'Before_Arrivals',
       'After_Arrivals', 'Before_Departures', 'After_Departures'],axis=1)

In [3326]:
#df2==taxi,df=arrival
t=0
for i in range(0,len(df)):
    if (abs(df.iloc[i,13]==point12[13]) and (df.iloc[i,0]==point12[0]) and (df.iloc[i,1]==point12[1])):
            t=i
            break
    if (abs(df.iloc[i,13]-point12[13])<=d and (df.iloc[i,0]==point12[0]) and (df.iloc[i,1]==point12[1])):
            t=i
            d=abs(df.iloc[i,9]-point12[9])
point12[14:26]=df.iloc[t,14:26]

In [3327]:
arr6=model2.predict(point12)
arr6

array([3.5279692])

In [3328]:
j_delay7=arr6-point12['DEP_DELAY']
j_delay7

array([12.08198324])

In [3329]:
k=19.4

In [3330]:
point7['DEP_DELAY']=k+5


In [3331]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df2)):
    if (abs(df2.iloc[i,9]==point7[9]) and (df2.iloc[i,0]==point7[0]) and (df2.iloc[i,1]==point7[1])):
            t=i
            break
    if (abs(df2.iloc[i,9]-point7[9])<=d and (df2.iloc[i,0]==point7[0]) and (df2.iloc[i,1]==point7[1])):
            t=i
            d=abs(df2.iloc[i,9]-point7[9])
point7[11:23]=df2.iloc[t,11:23]

In [3332]:
taxi4=model1.predict(point7)
taxi4[0]

16.078461754179948

In [3333]:
point8=point7.rename({"DEST":"ORIGIN"})
point8['ORIGIN']=33
point8['OP_UNIQUE_CARRIER']=2
point8['TAXI_OUT']=taxi4[0]
point8['WHEELS_OFF_M']=point8['DEP_TIME_M']+taxi4[0]
point8['Pred_Wheels_On']=point8['CRS_ARR_M']+point8['DEP_DELAY']-8
point8=point8.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'ORIGIN',
       'DEP_DELAY', 'TAXI_OUT', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M',
       'DEP_TIME_M', 'WHEELS_OFF_M', 'CRS_ARR_M', 'Pred_Wheels_On',
       'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed',
       'Wind Gust', 'Pressure', 'Condition', 'Before_Arrivals',
       'After_Arrivals', 'Before_Departures', 'After_Departures'],axis=1)

In [3334]:
#df2==taxi,df=arrival
t=0
for i in range(0,len(df)):
    if (abs(df.iloc[i,13]==point8[13]) and (df.iloc[i,0]==point8[0]) and (df.iloc[i,1]==point8[1])):
            t=i
            break
    if (abs(df.iloc[i,13]-point8[13])<=d and (df.iloc[i,0]==point8[0]) and (df.iloc[i,1]==point8[1])):
            t=i
            d=abs(df.iloc[i,9]-point8[9])
point8[14:26]=df.iloc[t,14:26]

In [3335]:
arr4=model2.predict(point8)
arr4

array([19.91065386])

In [3336]:
j_delay5=arr4-point8['DEP_DELAY']
j_delay5

array([-4.48934614])

In [3337]:
point7['DEP_DELAY']=k+10


In [3338]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df2)):
    if (abs(df2.iloc[i,9]==point7[9]) and (df2.iloc[i,0]==point7[0]) and (df2.iloc[i,1]==point7[1])):
            t=i
            break
    if (abs(df2.iloc[i,9]-point7[9])<=d and (df2.iloc[i,0]==point7[0]) and (df2.iloc[i,1]==point7[1])):
            t=i
            d=abs(df2.iloc[i,9]-point7[9])
point7[11:23]=df2.iloc[t,11:23]

In [3339]:
taxi4=model1.predict(point7)
taxi4[0]

16.701704124086582

In [3340]:
point8=point7.rename({"DEST":"ORIGIN"})
point8['ORIGIN']=33
point8['OP_UNIQUE_CARRIER']=2
point8['TAXI_OUT']=taxi4[0]
point8['WHEELS_OFF_M']=point8['DEP_TIME_M']+taxi4[0]
point8['Pred_Wheels_On']=point8['CRS_ARR_M']+point8['DEP_DELAY']-8
point8=point8.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'ORIGIN',
       'DEP_DELAY', 'TAXI_OUT', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M',
       'DEP_TIME_M', 'WHEELS_OFF_M', 'CRS_ARR_M', 'Pred_Wheels_On',
       'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed',
       'Wind Gust', 'Pressure', 'Condition', 'Before_Arrivals',
       'After_Arrivals', 'Before_Departures', 'After_Departures'],axis=1)

In [3341]:
#df2==taxi,df=arrival
t=0
for i in range(0,len(df)):
    if (abs(df.iloc[i,13]==point8[13]) and (df.iloc[i,0]==point8[0]) and (df.iloc[i,1]==point8[1])):
            t=i
            break
    if (abs(df.iloc[i,13]-point8[13])<=d and (df.iloc[i,0]==point8[0]) and (df.iloc[i,1]==point8[1])):
            t=i
            d=abs(df.iloc[i,9]-point8[9])
point8[14:26]=df.iloc[t,14:26]

In [3342]:
arr4=model2.predict(point8)
arr4

array([22.43640685])

In [3343]:
j_delay5=arr4-point8['DEP_DELAY']
j_delay5

array([-6.96359315])

In [3344]:
point7['DEP_DELAY']=k-5


In [3345]:
#df2==taxi,df=arrival
t=0
d=10000
for i in range(0,len(df2)):
    if (abs(df2.iloc[i,9]==point7[9]) and (df2.iloc[i,0]==point7[0]) and (df2.iloc[i,1]==point7[1])):
            t=i
            break
    if (abs(df2.iloc[i,9]-point7[9])<=d and (df2.iloc[i,0]==point7[0]) and (df2.iloc[i,1]==point7[1])):
            t=i
            d=abs(df2.iloc[i,9]-point7[9])
point7[11:23]=df2.iloc[t,11:23]

In [3346]:
taxi4=model1.predict(point7)
taxi4[0]

16.434789967365766

In [3347]:
point8=point7.rename({"DEST":"ORIGIN"})
point8['ORIGIN']=33
point8['OP_UNIQUE_CARRIER']=2
point8['TAXI_OUT']=taxi4[0]
point8['WHEELS_OFF_M']=point8['DEP_TIME_M']+taxi4[0]
point8['Pred_Wheels_On']=point8['CRS_ARR_M']+point8['DEP_DELAY']-8
point8=point8.reindex(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'ORIGIN',
       'DEP_DELAY', 'TAXI_OUT', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M',
       'DEP_TIME_M', 'WHEELS_OFF_M', 'CRS_ARR_M', 'Pred_Wheels_On',
       'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed',
       'Wind Gust', 'Pressure', 'Condition', 'Before_Arrivals',
       'After_Arrivals', 'Before_Departures', 'After_Departures'],axis=1)

In [3348]:
#df2==taxi,df=arrival
t=0
for i in range(0,len(df)):
    if (abs(df.iloc[i,13]==point8[13]) and (df.iloc[i,0]==point8[0]) and (df.iloc[i,1]==point8[1])):
            t=i
            break
    if (abs(df.iloc[i,13]-point8[13])<=d and (df.iloc[i,0]==point8[0]) and (df.iloc[i,1]==point8[1])):
            t=i
            d=abs(df.iloc[i,9]-point8[9])
point8[14:26]=df.iloc[t,14:26]

In [3349]:
arr4=model2.predict(point8)
arr4

array([11.15033295])

In [3350]:
j_delay5=arr4-point8['DEP_DELAY']
j_delay5

array([-3.24966705])